### ISSUE TITLE
Search options do not fit in ligth_box

### ISSUE THREAD

**Issue by gerard-kanters** [Centillien/more_solr#4]
When opening  the advanced search options a light box opens. However the search options are displayed as a horizontal box across the screen

**Comment by gerard-kanters** [comment]
Now light box is gone, but issue remains. Also type ahead is not working.

**Comment by nielsvandenboogaart** [comment]
Light box has been removed, type ahead wasn't backwards compatible.

Type ahead in user search should be working now.
